global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #  monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.50.4:9091']

  - job_name: 'serv1'
    static_configs:
      - targets: ['192.168.50.4:9100']

  - job_name: 'serv2'
    static_configs:
      - targets: ['192.168.50.5:9100']

  - job_name: 'serv3'
    static_configs:
      - targets: ['192.168.50.6:9100']

  - job_name: 'serv4'
    static_configs:
      - targets: ['192.168.50.7:9100']
